### ISSUE TITLE
مشكلة مع pyinstaller 

### ISSUE THREAD

**Issue by asgore-undertale** [mpcabd/python-arabic-reshaper#55]
السلام عليكم أخي
واجهت مشكلة أثناء تحويل مشروعي لملف تنفيذي
وبعد فترة علمت أن المشكلة من استيراد arabic-reshaper
هل هناك ما علي فعله لأحل المشكلة؟

**Comment by ahmed4end** [comment]
اكتب الخطأ اللى بيظهرلك ! @asgore-undertale

**Comment by asgore-undertale** [comment]
Traceback (most recent call last):
  File "Text Enteror 1.0v.py", line 9, in <module>
    import arabic_reshaper
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\023\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "arabic_reshaper\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\023\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "arabic_reshaper\arabic_reshaper.py", line 242, in <module>
  File "arabic_reshaper\arabic_reshaper.py", line 64, in __init__
  File "arabic_reshaper\reshaper_config.py", line 41, in auto_config
Exception: Default configuration file C:\Users\023\AppData\Local\Temp\_MEI64162\arabic_reshaper\default-config.ini not found, check the module installation.
[6968] Failed to execute script Text Enteror 1.0v

**Comment by ahmed4end** [comment]
@asgore-undertale 
تمام الحل بسيط جداً 
اذهب للمسار التالى عندك على الجهاز:
C:\Users\023\AppData\Local\Temp_MEI64162\arabic_reshaper
من قم الملف صاحب الاأسم:
default-config.ini
بعدها انسخه لمسار البرنامج اللى انت حولته ب pyinstaller 
واصنع ملف جديد هناك اسمه:
arabic_reshaper
َمن ثم ضع بداخله الملف اللى انت نسخته 
وبعدها شغل البرنامج بتاعك وهيشتغل بدون أخطاء

**Comment by ahmed4end** [comment]
@asgore-undertale 
المشكلة بسيطة جداً بدك تروح لمكان تنصيب بايثون وتفتح ملف تنصيب المكتبة 
arabic_reshaper
وتنسخ ملف 
default-config.ini 
وتروح تحطه فالبرنامج بتاعك اللى حولته ب pyiinstaller 
وتحطه هناك بداخل ملف باسم 
arabic_reshaper

**Comment by asgore-undertale** [comment]
شكرا جزيلا أخي
لكني بالفعل برمجت كود خاص بي لأنني عجزت عن حلها.

**Comment by mpcabd** [comment]
This is fixed in release 2.1.3, please upgrade, test, and let me know if it's still broken.
