### ISSUE TITLE
arabic_reshaper not working on Android

### ISSUE THREAD

**Issue by mehdializade** [mpcabd/python-arabic-reshaper#60]
arabic_reshaper working fine with windows and linux but when I run it as apk file in android, App crashed.
My errors is:

```
python  :  Traceback (most recent call last):
python  :    File "/media/mehdi/2436ef15-26cf-4be8-9eed-6befb73eddd8/mehdi/Documents/BuildozerTest/.buildozer/android/app/main.py", line 18, in <module>
python  :    File "/media/mehdi/2436ef15-26cf-4be8-9eed-6befb73eddd8/mehdi/Documents/BuildozerTest/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/FinalAPP/arabic_reshaper/__init__.py", line 12, in <module>
python  :  FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.test.finalapp/files/app/_python_bundle/site-packages/arabic_reshaper/__version__.py'
python  : Python for android ended.
```
In line 18, imported `arabic_reshaper` 
I would greatly appreciate it if you kindly help me

**Comment by mpcabd** [comment]
This is fixed in release 2.1.3, please upgrade, test, and let me know if it's still broken.
